In [3]:
import pandas as pd
import numpy as np
import datetime
import time

In [2]:
df = pd.read_csv("../data/20200715.csv")
df.head()

,data_flag,账户ID,账户名称,资质客户ID,客户名称,订单行,总消费,搜索点击消费,凤巢阿拉丁消费,超投已还消费,...,原生阿拉丁消费,原生CPC消费,原生CPM消费,百意Feed消费,百意无线开屏CPC消费,原生GD消费,百意FeedGD消费,原生CPC优惠券消费,原生CPM优惠券消费,慧合CPT消费
0,20200707,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,19643.59,5776.14,0.0,0.0,...,0.0,4331.46,9535.99,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20200708,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,15386.76,3702.67,0.0,0.0,...,0.0,3272.55,8411.54,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20200709,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,11374.74,3289.42,0.0,0.0,...,0.0,2690.88,5394.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20200710,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,13678.60,4150.55,0.0,0.0,...,0.0,2857.88,6670.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20200711,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,15936.26,5871.37,0.0,0.0,...,0.0,2788.12,7276.77,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
dtime = datetime.datetime.now()
dtime

datetime.datetime(2020, 7, 15, 11, 55, 34, 157260)

In [5]:
dtime = time.strftime("%Y%m%d",time.localtime())
dtime

'20200715'

In [24]:
dtime_f = int(dtime)-1
dtime_f

20200714

In [7]:
path = dtime + ".csv"
path

'20200715.csv'

In [8]:
df_d = pd.read_csv("../data/{}".format(path))
df_d.head()

,data_flag,账户ID,账户名称,资质客户ID,客户名称,订单行,总消费,搜索点击消费,凤巢阿拉丁消费,超投已还消费,...,原生阿拉丁消费,原生CPC消费,原生CPM消费,百意Feed消费,百意无线开屏CPC消费,原生GD消费,百意FeedGD消费,原生CPC优惠券消费,原生CPM优惠券消费,慧合CPT消费
0,20200707,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,19643.59,5776.14,0.0,0.0,...,0.0,4331.46,9535.99,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,20200708,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,15386.76,3702.67,0.0,0.0,...,0.0,3272.55,8411.54,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,20200709,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,11374.74,3289.42,0.0,0.0,...,0.0,2690.88,5394.44,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,20200710,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,13678.60,4150.55,0.0,0.0,...,0.0,2857.88,6670.17,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,20200711,28455179,车前草计算机科技,200211343,河南车前草计算机科技有限公司,0,15936.26,5871.37,0.0,0.0,...,0.0,2788.12,7276.77,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
df_d.columns

Index(['data_flag', '账户ID', '账户名称', '资质客户ID', '客户名称', '订单行', '总消费', '搜索点击消费',
       '凤巢阿拉丁消费', '超投已还消费', '凤巢优惠券消费', '阿拉丁CPT消费', '原生阿拉丁消费', '原生CPC消费',
       '原生CPM消费', '百意Feed消费', '百意无线开屏CPC消费', '原生GD消费', '百意FeedGD消费',
       '原生CPC优惠券消费', '原生CPM优惠券消费', '慧合CPT消费'],
      dtype='object')

In [12]:
df["总消"] = df_d["总消费"]-df_d["凤巢优惠券消费"]-df_d["原生CPC优惠券消费"]-df_d["原生CPM优惠券消费"]
df["总消"].sum()

11892545.08

In [13]:
df["信息流"] = df_d["阿拉丁CPT消费"]+df_d["原生阿拉丁消费"]+df_d["原生CPC消费"]+df_d["原生CPM消费"]+df_d["百意Feed消费"]+df_d["百意无线开屏CPC消费"]+df_d["原生GD消费"]+df_d["百意FeedGD消费"]-df_d["原生CPC优惠券消费"]-df_d["原生CPM优惠券消费"]
df["信息流"].sum()

4535522.16

In [14]:
df[df["data_flag"]>=20200701]["信息流"].sum()

2058017.2799999998

In [15]:
df[df["data_flag"]>=20200701]["总消"].sum()

5598705.78

In [16]:
df["搜索消费"] = df["搜索点击消费"] + df["凤巢阿拉丁消费"] - df["凤巢优惠券消费"]
df[df["data_flag"]>=20200701]["搜索消费"].sum()

3390110.02

In [20]:
df[["data_flag","客户名称","总消","信息流","搜索消费"]].groupby(by=["data_flag","客户名称"]).sum()

                                 总消      信息流      搜索消费
data_flag 客户名称
20200614  中国共产党郑州市委员会宣传部    4293.82     0.00      0.00
          信阳市浉河区人民政府办公室      263.00     0.00      0.00
          南阳天之翊网络科技有限公司      145.83   145.83      0.00
          南阳绿莹艾草生物制品有限公司     207.89   207.89      0.00
          博凯健康产业有限公司        2006.19  1001.64   1004.55
...                             ...      ...       ...
20200714  郑州达人视界职业培训学校      2060.07   511.40   1548.67
          郑州雅方教育信息咨询有限公司   38990.56  1145.72  37254.91
          郑州雅方教育研究院(普通合伙)  29885.63  1833.90  28051.73
          郑州香雪儿食品有限公司         98.97     0.00      0.00
          郑州龙宝行汽车销售服务有限公司    603.01   603.01      0.00

[2966 rows x 3 columns]

In [26]:
today_data = df[df["data_flag"]==dtime_f][["总消费","信息流","搜索消费"]].sum()
today_data

总消费     411053.02
信息流     132169.57
搜索消费    267938.09
dtype: float64

In [27]:

y_data = df[df["data_flag"]==(dtime_f-1)][["总消费","信息流","搜索消费"]].sum()
y_data

总消费     429748.56
信息流     149300.56
搜索消费    269348.45
dtype: float64

In [32]:
df[df["客户名称"]=="郑州雅方教育信息咨询有限公司"]["总消"]/2

914     4074.705
915     4227.600
916     3373.595
917     4349.045
918     3849.890
          ...
4756     169.240
4757     520.240
4758     527.010
4759     604.260
4760     698.460
Name: 总消, Length: 106, dtype: float64

In [34]:
df[df["客户名称"]=="郑州雅方教育信息咨询有限公司"][["总消","信息流","搜索消费"]] = df[df["客户名称"]=="郑州雅方教育信息咨询有限公司"][["总消","信息流","搜索消费"]]/2

d:\python\lib\site-packages\pandas\core\frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [35]:
df[df["客户名称"]=="郑州雅方教育信息咨询有限公司"]["总消"]

914     8149.41
915     8455.20
916     6747.19
917     8698.09
918     7699.78
         ...
4756     338.48
4757    1040.48
4758    1054.02
4759    1208.52
4760    1396.92
Name: 总消, Length: 106, dtype: float64

In [53]:
data = df[["data_flag","客户名称","总消","信息流","搜索消费"]].copy()
data.head()

   data_flag            客户名称        总消       信息流     搜索消费
0   20200707  河南车前草计算机科技有限公司  19643.59  13867.45  5776.14
1   20200708  河南车前草计算机科技有限公司  15386.76  11684.09  3702.67
2   20200709  河南车前草计算机科技有限公司  11374.74   8085.32  3289.42
3   20200710  河南车前草计算机科技有限公司  13678.60   9528.05  4150.55
4   20200711  河南车前草计算机科技有限公司  15936.26  10064.89  5871.37

In [50]:
data[data["客户名称"]=="郑州雅方教育信息咨询有限公司" ][["总消","信息流","搜索消费"]]/2

            总消      信息流      搜索消费
914   4074.705  261.675  3813.030
915   4227.600  346.840  3880.760
916   3373.595  640.720  2732.875
917   4349.045  772.875  3576.170
918   3849.890  572.860  3277.030
...        ...      ...       ...
4756   169.240    0.000   114.535
4757   520.240    0.000   457.610
4758   527.010    0.000   466.405
4759   604.260    0.000   539.250
4760   698.460    0.000   641.025

[106 rows x 3 columns]

In [54]:
data.loc[data["客户名称"]=="郑州雅方教育信息咨询有限公司" ,"总消"] = (data[data["客户名称"]=="郑州雅方教育信息咨询有限公司"]["总消"])/2
data.loc[data["客户名称"]=="郑州雅方教育信息咨询有限公司" ,"信息流"] = (data[data["客户名称"]=="郑州雅方教育信息咨询有限公司"]["信息流"])/2
data.loc[data["客户名称"]=="郑州雅方教育信息咨询有限公司" ,"搜索消费"] = (data[data["客户名称"]=="郑州雅方教育信息咨询有限公司"]["搜索消费"])/2


data[data["客户名称"]=="郑州雅方教育信息咨询有限公司" ]

      data_flag            客户名称        总消      信息流      搜索消费
914    20200710  郑州雅方教育信息咨询有限公司  4074.705  261.675  3813.030
915    20200711  郑州雅方教育信息咨询有限公司  4227.600  346.840  3880.760
916    20200712  郑州雅方教育信息咨询有限公司  3373.595  640.720  2732.875
917    20200713  郑州雅方教育信息咨询有限公司  4349.045  772.875  3576.170
918    20200714  郑州雅方教育信息咨询有限公司  3849.890  572.860  3277.030
...         ...             ...       ...      ...       ...
4756   20200701  郑州雅方教育信息咨询有限公司   169.240    0.000   114.535
4757   20200702  郑州雅方教育信息咨询有限公司   520.240    0.000   457.610
4758   20200703  郑州雅方教育信息咨询有限公司   527.010    0.000   466.405
4759   20200704  郑州雅方教育信息咨询有限公司   604.260    0.000   539.250
4760   20200705  郑州雅方教育信息咨询有限公司   698.460    0.000   641.025

[106 rows x 5 columns]

In [48]:
column = ["郑州雅方教育研究院(普通合伙)","郑州雅方教育信息咨询有限公司"]

In [61]:
data[data["客户名称"]=="郑州雅方教育研究院(普通合伙)"]

      data_flag             客户名称       总消  信息流     搜索消费
121    20200624  郑州雅方教育研究院(普通合伙)   236.52  0.0   236.52
122    20200625  郑州雅方教育研究院(普通合伙)   990.21  0.0   990.21
123    20200626  郑州雅方教育研究院(普通合伙)  2668.22  0.0  2668.22
124    20200627  郑州雅方教育研究院(普通合伙)  3496.96  0.0  3496.96
125    20200628  郑州雅方教育研究院(普通合伙)  4110.82  0.0  4110.82
...         ...              ...      ...  ...      ...
3457   20200705  郑州雅方教育研究院(普通合伙)  9999.81  0.0  9999.81
3458   20200706  郑州雅方教育研究院(普通合伙)  7527.78  0.0  7527.78
3459   20200707  郑州雅方教育研究院(普通合伙)  9391.45  0.0  9391.45
3460   20200708  郑州雅方教育研究院(普通合伙)  5264.72  0.0  5264.72
3461   20200709  郑州雅方教育研究院(普通合伙)  4263.39  0.0  4263.39

[113 rows x 5 columns]

In [58]:
data

      data_flag            客户名称        总消       信息流     搜索消费
0      20200707  河南车前草计算机科技有限公司  19643.59  13867.45  5776.14
1      20200708  河南车前草计算机科技有限公司  15386.76  11684.09  3702.67
2      20200709  河南车前草计算机科技有限公司  11374.74   8085.32  3289.42
3      20200710  河南车前草计算机科技有限公司  13678.60   9528.05  4150.55
4      20200711  河南车前草计算机科技有限公司  15936.26  10064.89  5871.37
...         ...             ...       ...       ...      ...
5400   20200708      郑州佳龙食品有限公司    266.66      0.00     0.00
5401   20200709      郑州佳龙食品有限公司    266.66      0.00     0.00
5402   20200710      郑州佳龙食品有限公司    266.66      0.00     0.00
5403   20200711      郑州佳龙食品有限公司    266.66      0.00     0.00
5404   20200712      郑州佳龙食品有限公司    266.66      0.00     0.00

[5405 rows x 5 columns]

In [62]:
data.loc[data["客户名称"]=="郑州雅方教育研究院(普通合伙)" ,"总消"] = (data[data["客户名称"]=="郑州雅方教育研究院(普通合伙)"]["总消"])/2
data.loc[data["客户名称"]=="郑州雅方教育研究院(普通合伙)" ,"信息流"] = (data[data["客户名称"]=="郑州雅方教育研究院(普通合伙)"]["信息流"])/2
data.loc[data["客户名称"]=="郑州雅方教育研究院(普通合伙)" ,"搜索消费"] = (data[data["客户名称"]=="郑州雅方教育研究院(普通合伙)"]["搜索消费"])/2


data[data["客户名称"]=="郑州雅方教育研究院(普通合伙)" ]

      data_flag             客户名称        总消  信息流      搜索消费
121    20200624  郑州雅方教育研究院(普通合伙)   118.260  0.0   118.260
122    20200625  郑州雅方教育研究院(普通合伙)   495.105  0.0   495.105
123    20200626  郑州雅方教育研究院(普通合伙)  1334.110  0.0  1334.110
124    20200627  郑州雅方教育研究院(普通合伙)  1748.480  0.0  1748.480
125    20200628  郑州雅方教育研究院(普通合伙)  2055.410  0.0  2055.410
...         ...              ...       ...  ...       ...
3457   20200705  郑州雅方教育研究院(普通合伙)  4999.905  0.0  4999.905
3458   20200706  郑州雅方教育研究院(普通合伙)  3763.890  0.0  3763.890
3459   20200707  郑州雅方教育研究院(普通合伙)  4695.725  0.0  4695.725
3460   20200708  郑州雅方教育研究院(普通合伙)  2632.360  0.0  2632.360
3461   20200709  郑州雅方教育研究院(普通合伙)  2131.695  0.0  2131.695

[113 rows x 5 columns]

In [63]:
data[data["data_flag"]==20200714].groupby(by=["客户名称"]).sum()

                 data_flag         总消      信息流       搜索消费
客户名称
中国共产党郑州市委员会宣传部    20200714   4293.820     0.00      0.000
信阳市浉河区人民政府办公室     20200714    263.000     0.00      0.000
华知企业服务集团有限公司      40401428   9498.610  9498.61      0.000
博凯健康产业有限公司        20200714   1962.400   958.57   1003.830
博凯药业有限公司          20200714    300.880     0.00    300.880
...                    ...        ...      ...        ...
郑州达人视界职业培训学校      20200714   2060.070   511.40   1548.670
郑州雅方教育信息咨询有限公司    80802856  19495.280   572.86  18627.455
郑州雅方教育研究院(普通合伙)   80802856  14942.815   916.95  14025.865
郑州香雪儿食品有限公司       20200714     98.970     0.00      0.000
郑州龙宝行汽车销售服务有限公司   20200714    603.010   603.01      0.000

[94 rows x 4 columns]

In [69]:
data[data["data_flag"]==20200714][["总消","信息流","搜索消费"]].sum()-data[data["data_flag"]==20200713][["总消","信息流","搜索消费"]].sum()

总消     -20380.390
信息流    -16868.160
搜索消费    -3394.475
dtype: float64

In [70]:
d = data.groupby(by=["data_flag","客户名称"]).sum()

In [74]:
d

                                  总消      信息流       搜索消费
data_flag 客户名称
20200614  中国共产党郑州市委员会宣传部    4293.820     0.00      0.000
          信阳市浉河区人民政府办公室      263.000     0.00      0.000
          南阳天之翊网络科技有限公司      145.830   145.83      0.000
          南阳绿莹艾草生物制品有限公司     207.890   207.89      0.000
          博凯健康产业有限公司        2006.190  1001.64   1004.550
...                              ...      ...        ...
20200714  郑州达人视界职业培训学校      2060.070   511.40   1548.670
          郑州雅方教育信息咨询有限公司   19495.280   572.86  18627.455
          郑州雅方教育研究院(普通合伙)  14942.815   916.95  14025.865
          郑州香雪儿食品有限公司         98.970     0.00      0.000
          郑州龙宝行汽车销售服务有限公司    603.010   603.01      0.000

[2966 rows x 3 columns]

In [77]:
now_data = data[data["data_flag"]==20200714].groupby(by="客户名称").sum()
now_data

                 data_flag         总消      信息流       搜索消费
客户名称
中国共产党郑州市委员会宣传部    20200714   4293.820     0.00      0.000
信阳市浉河区人民政府办公室     20200714    263.000     0.00      0.000
华知企业服务集团有限公司      40401428   9498.610  9498.61      0.000
博凯健康产业有限公司        20200714   1962.400   958.57   1003.830
博凯药业有限公司          20200714    300.880     0.00    300.880
...                    ...        ...      ...        ...
郑州达人视界职业培训学校      20200714   2060.070   511.40   1548.670
郑州雅方教育信息咨询有限公司    80802856  19495.280   572.86  18627.455
郑州雅方教育研究院(普通合伙)   80802856  14942.815   916.95  14025.865
郑州香雪儿食品有限公司       20200714     98.970     0.00      0.000
郑州龙宝行汽车销售服务有限公司   20200714    603.010   603.01      0.000

[94 rows x 4 columns]

In [80]:
yet_data = data[data["data_flag"]==20200713].groupby(by="客户名称").sum()
yet_data.columns

Index(['data_flag', '总消', '信息流', '搜索消费'], dtype='object')

In [85]:
yet_data.iloc[:,1]

客户名称
中国共产党郑州市委员会宣传部      4293.820
信阳市浉河区人民政府办公室        263.000
华知企业服务集团有限公司        9070.580
博凯健康产业有限公司          2511.900
博凯药业有限公司             306.700
                     ...
郑州达人视界职业培训学校        1705.500
郑州雅方教育信息咨询有限公司     18793.035
郑州雅方教育研究院(普通合伙)    13960.210
郑州香雪儿食品有限公司          197.940
郑州龙宝行汽车销售服务有限公司      634.700
Name: 总消, Length: 93, dtype: float64

In [88]:
#new_data["客户名称"] = now_data.iloc[:,1]
now_data["总消环比"] = now_data["总消"] - yet_data["总消"]
now_data["信息流环比"] = now_data["信息流"] - yet_data["信息流"]
now_data["搜索环比"] = now_data["搜索消费"] - yet_data["搜索消费"]
now_data

,data_flag,总消,信息流,搜索消费,总消环比,信息流环比,搜索环比
客户名称,,,,,,,
中国共产党郑州市委员会宣传部,20200714,4293.820,0.00,0.000,0.000,0.000,0.000
信阳市浉河区人民政府办公室,20200714,263.000,0.00,0.000,0.000,0.000,0.000
华知企业服务集团有限公司,40401428,9498.610,9498.61,0.000,428.030,428.030,0.000
博凯健康产业有限公司,20200714,1962.400,958.57,1003.830,-549.500,-552.630,3.130
博凯药业有限公司,20200714,300.880,0.00,300.880,-5.820,0.000,-5.820
...,...,...,...,...,...,...,...
郑州达人视界职业培训学校,20200714,2060.070,511.40,1548.670,354.570,262.730,91.840
郑州雅方教育信息咨询有限公司,80802856,19495.280,572.86,18627.455,702.245,-200.015,938.695
郑州雅方教育研究院(普通合伙),80802856,14942.815,916.95,14025.865,982.605,-62.815,1045.420
郑州香雪儿食品有限公司,20200714,98.970,0.00,0.000,-98.970,0.000,0.000
郑州龙宝行汽车销售服务有限公司,20200714,603.010,603.01,0.000,-31.690,-31.690,0.000

In [98]:
ddd = now_data.sort_values(by="总消环比",ascending=True,ignore_index=False)

In [102]:
ddd.to_csv("../data/data.csv",encoding="utf_8_sig")

In [105]:
ddd.columns

Index(['data_flag', '总消', '信息流', '搜索消费', '总消环比', '信息流环比', '搜索环比'], dtype='object')

In [107]:
ddd.count()

data_flag    94
总消           94
信息流          94
搜索消费         94
总消环比         91
信息流环比        91
搜索环比         91
dtype: int64

In [97]:
clicent = df.groupby(by="客户名称").count()

,data_flag,账户ID,账户名称,资质客户ID,订单行,总消费,搜索点击消费,凤巢阿拉丁消费,超投已还消费,凤巢优惠券消费,...,百意Feed消费,百意无线开屏CPC消费,原生GD消费,百意FeedGD消费,原生CPC优惠券消费,原生CPM优惠券消费,慧合CPT消费,总消,信息流,搜索消费
客户名称,,,,,,,,,,,,,,,,,,,,,
中国共产党郑州市委员会宣传部,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
信阳市浉河区人民政府办公室,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
华知企业服务集团有限公司,24,24,24,24,24,24,24,24,24,24,...,24,24,24,24,24,24,24,24,24,24
南阳天之翊网络科技有限公司,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
南阳绿莹艾草生物制品有限公司,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
郑州达人视界职业培训学校,31,31,31,31,31,31,31,31,31,31,...,31,31,31,31,31,31,31,31,31,31
郑州雅方教育信息咨询有限公司,106,106,106,106,106,106,106,106,106,106,...,106,106,106,106,106,106,106,106,106,106
郑州雅方教育研究院(普通合伙),113,113,113,113,113,113,113,113,113,113,...,113,113,113,113,113,113,113,113,113,113
郑州香雪儿食品有限公司,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
郑州龙宝行汽车销售服务有限公司,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9

In [ ]:
pd.merge()